# Generated by Django 4.1.2 on 2023-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=122)),
                ('event_time', models.DateTimeField(max_length=122)),
                ('event_img', models.ImageField(upload_to='static/event_images/')),
                ('event_data', models.TextField(default=100)),
                ('event_loc', models.TextField(max_length=122)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_liked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('mob', models.IntegerField()),
                ('password', models.CharField(max_length=122, unique=True)),
                ('email', models.CharField(max_length=122)),
            ],
        ),
    ]
